name: Test CLI scripts

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install python dependencies
        run: |
          pip install poetry
          poetry install --extras "full"
      - name: Download benchmark data
        run: |
          wget -O benchmark_data.zip "https://drive.google.com/uc?export=download&id=1NHrdYatR1rtqs2gPVfdvO0BAvocH8CJi"
          unzip -o benchmark_data.zip
      - name: Test single script
        run: poetry run marker_single benchmark_data/pdfs/switch_trans.pdf --page_range 0
      - name: Test convert script
        run: poetry run marker benchmark_data/pdfs --max_files 1 --workers 1 --page_range 0
      - name: Text convert script multiple workers
        run: poetry run marker benchmark_data/pdfs --max_files 2 --workers 2 --page_range 0-5